-- Migration: Add safety_article_jsonb column for "Is X Safe?" SEO pages
-- ============================================================
-- Each product gets a cached AI-generated safety Q&A article.
-- Generated on-demand via Gemini + FDA data, stored in JSONB.
-- Drives long-tail search traffic ("is melatonin safe", "is retinol safe during pregnancy").

alter table public.medications
  add column if not exists safety_article_jsonb jsonb,
  add column if not exists safety_article_generated_at timestamptz;

comment on column public.medications.safety_article_jsonb is
  'Structured safety Q&A content for /is-safe/[slug] page. Generated by generateSafetyArticle().';

-- Index for cron jobs that find products needing safety articles
create index if not exists idx_medications_safety_missing
  on public.medications(approval_status)
  where safety_article_jsonb is null and approval_status = 'approved';
